services:
  web:
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - /home/c/cc-odoo18/myaddons:/mnt/extra-addons
      - /home/c/conf/odoo.conf:/etc/odoo/odoo_main.conf       
      - /home/c/cc-odoo18/myaddonspathdir.conf:/etc/odoo/odoo_addons.conf 
    env_file: /home/c/conf/.env
    command: -c /etc/odoo/odoo_main.conf -c /etc/odoo/odoo_addons.conf

    env_file: /home/c/conf/.env
    restart: always
  db:
    image: postgres:15
    env_file: /home/c/conf/.env
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    restart: always
volumes:
  odoo-web-data:
  odoo-db-data:


