services:
  web:
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - /home/c/cc-odoo18/myaddons/cysbros:/mnt/extra-addons/cysbros
      - /home/c/cc-odoo18/myaddons/oca-account-financial-tools-18.0:/mnt/extra-addons/oca-account-financial-tools-18.0
      - /home/c/cc-odoo18/config:/etc/odoo
    env_file: /home/c/conf/.env
    restart: always
  db:
    image: postgres:15
    env_file: /home/c/conf/.env
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    restart: always
volumes:
  odoo-web-data:
  odoo-db-data:

# volumes:
#  - /home/c/cc-odoo18/myaddons/carpeta_addons1:/mnt/extra-addons/carpeta_addons1
#  - /home/c/cc-odoo18/myaddons/carpeta_addons2:/mnt/extra-addons/carpeta_addons2
#  - /home/c/cc-odoo18/myaddons/otra_carpeta_addons:/mnt/extra-addons/otra_carpeta_addons
#  - /home/c/cc-odoo18/myaddons:/mnt/extra-addons # Si quieres incluir la raíz también

